_BASE_: ../base.yaml
MODEL:
  SEM_SEG_HEAD:
    NUM_CLASSES: 9
    TRAIN_CLASS_JSON: "datasets/openearthmap.json"
    TEST_CLASS_JSON: "datasets/openearthmap.json"
DATASETS:
  TRAIN: ("openearth_sem_seg_train",)
  TEST: ("openearth_sem_seg_val",)
SOLVER:
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 20000


